### PR TITLE
Java semantics update

### PR DESCRIPTION
**Pull request by danorris709**
Changes little things such as using the List interface as the variable type (rather than the ArrayList specifically) and using diamonds from the Java 7 update.

### CODE REVIEW

**Comment by finneyj** [comment]
Hi @danorris709 

Thanks for the PR.

This is a tricky one however. Generally, I agree with the change, and if this were simply an open source project, I'd be very happy to merge.

However... the purpose of this repo, as you well know, is to support first contact teaching of OO concepts. To do that, I intentionally avoided using mechanisms that such students aren't introduced too. So that if they look at the code, it maximizes the amount of code those student can understand.

If we were going for overall consistency and quality, we'd make much heavier use of inheritance for object types, polymorphism is the render list, method overloading in the add() methods etc. All of which would improve the code, but makes it harder for beginners to understand...

So i'm a little wary... 
I'd be very supportive of a parallel repo where we do all this and more though. 

Thoughts?

**Comment by finneyj** [comment]
@danorris709 I'm thinking we should perhaps create an unconstrained, long lived, "advanced" branch. 

What thinks?

**Comment by KMatthewMarsden** [comment]
I would also be interested in a parallel repository as I was thinking about how we might paint() more efficiently via the use of polymorphism and overloading in those methods. This could solve the issue some students are having with regards to layering, which I saw no real way of solving (efficiently at least) without changing the code in this way. Though I understand the reason for not including it at this point.

**Comment by danorris709** [comment]
Sorry didn't get the email for this as it went into the "forums" directory on gmail.
I think working on a second branch would certainly be interesting and could be valuable for anyone who wishes to explore further but is slightly unsure where to look.

**Pull request closed without merging**
